### ISSUE TITLE
bug: Firebase Messaging not initialized

### ISSUE THREAD

**Issue by phal0r** [capawesome-team/capacitor-firebase#142]
**Plugin(s):**
- @capacitor-firebase/messaging@0.5.0

**Platform(s):**
- ios

**Current behavior:**
I added the plugin to my capacitor app, set up push notifications and background modes. Added snippets as described to AppDelegate.swift and FirebaseAppDelegateProxyEnabled to Info.plist. Also added GoogleService-Info.plist to the xcode project.

After building and running the app on a mobile device, I see these errors in xcode logs:

```
[FirebaseCore][I-COR000003] The default Firebase app has not yet been configured. Add `FirebaseApp.configure()` to your application initialization. This can be done in in the App Delegate's application(_:didFinishLaunchingWithOptions:)` (or the `@main` struct's initializer in SwiftUI).

[FirebaseMessaging][I-FCM002023] The object <CapacitorFirebaseMessaging.FirebaseMessaging: 0x282da5380> does not respond to -messaging:didReceiveRegistrationToken:. Please implement -messaging:didReceiveRegistrationToken: to be provided with an FCM token.
```

**Expected behavior:**
No warnings of uninitialized Firebase components in xcode log.

**Steps to reproduce:**
build and run the app.

**Related code:**

**Other information:**

**Capacitor doctor:**

```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 3.6.0
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0

Installed Dependencies:

  @capacitor/cli: 3.5.1
  @capacitor/core: 3.6.0
  @capacitor/android: 3.6.0
  @capacitor/ios: 3.6.0

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

**Comment by robingenz** [comment]
Hi @phal0r,
thank you for your request.
Please provide a Minimal, Reproducible Example (see [How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)) so I can debug the issue.

**Comment by phal0r** [comment]
Ok, I will prepare a testrepo. For Android it works as expected, only iOS is affected.

**Comment by robingenz** [comment]
Thank you!

It may be that the warning appears because the plugin is not loading fast enough and takes a little longer to register. But I'm not sure if I could do anything about that. Is everything working besides that?

**Comment by phal0r** [comment]
@robingenz here is the reproduction: https://github.com/phal0r/push-test

my steps:
```
npm install
npx cap sync ios
npx cap open ios
<run from xcode on device>
```

xcode logs:
```
9.1.0 - [FirebaseCore][I-COR000003] The default Firebase app has not yet been configured. Add `FirebaseApp.configure()` to your application initialization. This can be done in in the App Delegate's application(_:didFinishLaunchingWithOptions:)` (or the `@main` struct's initializer in SwiftUI). Read more: https://goo.gl/ctyzm8.
9.1.0 - [FirebaseMessaging][I-FCM002022] APNS device token not set before retrieving FCM Token for Sender ID '*****'. Notifications to this FCM Token will not be delivered over APNS.Be sure to re-retrieve the FCM token once the APNS device token is set.
9.1.0 - [FirebaseMessaging][I-FCM002023] The object <CapacitorFirebaseMessaging.FirebaseMessaging: 0x281d5d120> does not respond to -messaging:didReceiveRegistrationToken:. Please implement -messaging:didReceiveRegistrationToken: to be provided with an FCM token.
```

Tried to send a broadcast notification from firebase console, but it does not work.

**Comment by phal0r** [comment]
I was debugging a little with xcode now and it works, but there are still some quirks:

`FirebaseApp.configure()` is executed on the main thread and has loaded the google plist properly, but still shows this warning of not being configured
-> Do you know, how we can prevent this?

`APNS device token not set before retrieving FCM Token...`
-> this always happen on first app start, so I think there is a kind of race condition, but I don't know enough to fully understand this, but I guess we should take this seriously
-> Is there anything we can do to fix this? Other plugins do not have this problem (I used capacitor-firebase-push before, but it is deprecated)

`The object <CapacitorFirebaseMessaging.FirebaseMessaging: 0x281d5d120> does not respond to -messaging:didReceiveRegistrationToken`
-> this is indeed missing and should be implemented according to the firebase docs

I was looking at the sourcecode and from my understanding on iOS, you return the APNS Token on `tokenReceived` event, but it should return the fcmToken according to the docs. So implementing `didReceiveRegistrationToken` on FirebaseMessaging should actually trigger the notifyListeners for `tokenReceived` (and will not emit the warning)

this code will return the apns token: https://github.com/capawesome-team/capacitor-firebase/blob/main/packages/messaging/ios/Plugin/FirebaseMessagingPlugin.swift#L188

this code will return the fcm token: https://github.com/capawesome-team/capacitor-firebase/blob/main/packages/messaging/ios/Plugin/FirebaseMessagingPlugin.swift#L63

And I think, that triggering an additional tokenReceived event on getToken is not needed. So both calls can be removed imho. My suggestion would be to add 

```
@objc public func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String?) {
            // call handleTokenReceived with fcmToken from here 
        }
```
to FirebaseMessaging in order to trigger the event with the correct token at the correct time. What do you think?

**Comment by robingenz** [comment]
Thanks for debugging!

> FirebaseApp.configure() is executed on the main thread and has loaded the google plist properly, but still shows this warning of not being configured
-> Do you know, how we can prevent this?

Configure a FirebaseApp instance in your App's delegate's application(_:didFinishLaunchingWithOptions:) method:
```swift
// Use Firebase library to configure APIs
FirebaseApp.configure()
```
This should remove the warning message.
It also works without, because the plugin does that too, but then the warning appears, because the plugin does a bit later. 

> APNS device token not set before retrieving FCM Token...
Is there anything we can do to fix this?

Make sure that everything is set up correctly (see [here](https://stackoverflow.com/a/69316428/6731412)).
This error message should, if everything is configured correctly, only occur at the first start. Once a token has been requested, this message should no longer appear.

> The object <CapacitorFirebaseMessaging.FirebaseMessaging: 0x281d5d120> does not respond to -messaging:didReceiveRegistrationToken
-> this is indeed missing and should be implemented according to the firebase docs

You are right! Looks like a bug. I created a fix (see #144). You can test the dev version if you want:

```
npm i @capacitor-firebase/messaging@0.5.0-dev.92c882e.1657824199
```

> but I think, that triggering an additional tokenReceived event on getToken is not needed.

I created a PR #145 and will think about that a few days. Since it is a breaking change, I will wait a bit with the release.

**Comment by robingenz** [comment]
> I have looked at the PR. I would suggest to keep handleTokenReceived method and add the following function to FirebaseMessaging.swift:

Sorry, I can' t follow you on that one. Do you want to make a PR with your proposal?

> Also my intention for the other 2 warnings is to improve the plugin and fix the warnings, not building something around it. I compared this plugin to capacitor/push-notifications, capacitor-community/fcm and capacitor-firebase-push and the only difference I could find is, that those plugins call UIApplication.shared.registerForRemoteNotifications() seperately triggered by the user, when calling register() after having the proper permissions (the register() semantics are comparable to getToken() in this plugin imho).

I would like to fix it too. What gives you the feeling that I want to build around it?
As I said before I can not call `FirebaseApp.configure()` earlier. You can remove the warning by calling it yourself
The error message `APNS device token not set before retrieving FCM Token...` I could not reproduce with my demo app and I assume it is a config error.
And the last point was clearly a bug (apnsToken is not an fcmToken) which I fixed.

Since the last two points has nothing to do with the original issue (`The default Firebase app has not yet been configured.`), I would suggest you create a new issue for this where we can discuss these points further.

**Comment by robingenz** [comment]
> You suggested to call FirebaseApp.configure() additionally somewhere in AppDelegate, so I probably misinterpreted it :)

No problem, I just want to make sure you didn't get it wrong 😄 

> So I think, that something else might trigger this warning and the function, where it is called right now, is totally fine.

That may be, but I can't think of what that could be at the moment.

> Currently I think, that both warnings are a result of the same problem. I will play around locally a bit to verify my theory (or drop it :D ).

👍 

> Ok, I can do that. I will try to get rid of the default Firebase App warning in this ticket and create a new one for the token handling and will reference a PR as a suggestion.

Great, thank you! I like to definitely solve the problem but work on everything separately from each other.

**Comment by phal0r** [comment]
Now I am messing around with the code locally, but no luck so far. I even put it in the launch method as suggested from you and the firebase docs:

```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
        if FirebaseApp.app() == nil {
            FirebaseApp.configure()
        }
        
        return true
    }
```

And I still get this warning. So something is wrong with my local test app. I will dig a little deeper.

**Comment by HeikoKanzler** [comment]
I just randomly came across this issue. I have a similar problem: fresh app, fresh install of Firebase (Analytics and Crashlytics) and it floods my logs with "No Firebase App '[DEFAULT]' has been created", both web and build on device. However, everything works as expected, it's only flooding my logs on each call to Firebase.

**Comment by robingenz** [comment]
@HeikoKanzler Please provide a minimal, reproducible example so I can debug it. I saw the message only one time at startup.
